// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAymnAm_KOZZ7MIDvuzMPQLMlcblXSCXhk',
    appId: '1:361396117618:web:c908a57de80b82323a22eb',
    messagingSenderId: '361396117618',
    projectId: 'postmanborrow',
    authDomain: 'postmanborrow.firebaseapp.com',
    storageBucket: 'postmanborrow.appspot.com',
  );

  static const FirebaseOptions android =
  FirebaseOptions(
    apiKey: 'AIzaSyDzkVLL77is2Gvamb-bLPZyEOpkn3_OaF4',
    appId: '1:361396117618:android:68d5d467e0cff1d03a22eb',
    messagingSenderId: '361396117618',
    projectId: 'postmanborrow',
    storageBucket: 'postmanborrow.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ95vtaQ4bpIADCUFCmo_LAGwVICAAYBc',
    appId: '1:361396117618:ios:0d61e0134df209e93a22eb',
    messagingSenderId: '361396117618',
    projectId: 'postmanborrow',
    storageBucket: 'postmanborrow.appspot.com',
    iosClientId: '361396117618-ami6v9lfrom82fq9k0kfs7riadcbggql.apps.googleusercontent.com',
    iosBundleId: 'com.example.postman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ95vtaQ4bpIADCUFCmo_LAGwVICAAYBc',
    appId: '1:361396117618:ios:e98b8c471d104fed3a22eb',
    messagingSenderId: '361396117618',
    projectId: 'postmanborrow',
    storageBucket: 'postmanborrow.appspot.com',
    iosClientId: '361396117618-1c2eku1tm10ia3utbl6dbkusvuon9vhs.apps.googleusercontent.com',
    iosBundleId: 'com.example.postman.RunnerTests',
  );
}
